### PR TITLE
Erefactor/v5 dev project/1/jdt/jdt remove all trailing whitespace clean up 3

### PR DESCRIPTION
**Pull request by cal101**
#### 说明

1. 请确认你提交的PR是到'v5-dev'分支，否则我会手动修改代码并关闭PR。
2. 请确认没有更改代码风格（如tab缩进）
3. 新特性添加请确认注释完备，如有必要，请在src/test/java下添加Junit测试用例

### 修改描述(包括说明bug修复或者添加新特性)

1. [bug修复] balabala……
2. [新特性]  balabala……

### CODE REVIEW

**Comment by looly** [comment]
please pr to `v5-dev`

**Comment by cal101** [comment]
Sorry, I forgot to switch the target branch.
Do you know any way to change the default?

I am restructuring the pipeline a little. Expect some more cleanups.
I am selecting the cleanups *I* consider useful or probably useful.
If you don't agree for some PR just say so in the comments and I disable that cleanup.

I check the PRs before submitting them and hold back wrong cleanups.
Please drop me a note in the PR if you find a wrong cleanup that I missed.

**Comment by looly** [comment]
sorry, I had expected you are the machine and pr automatic.

I will report the details next time if pr is invalid.

**Comment by looly** [comment]
Github can limit branch but I won't.

**Comment by cal101** [comment]
Automatic creation of PRs is not ready yet. Currently it is still manual  work.

**Comment by looly** [comment]
OK, thanks for your pr.

**Pull request closed without merging**
