### PR TITLE
kmp 重写indexOf

### PR DESCRIPTION
**Pull request by tgiwu**
1. StrUtil中添加indexOf和contains方法，使用kmp重写
2. 添加测试用例，保证与jdk中String的原生方法有相同返回值

### CODE REVIEW

**Comment by looly** [comment]
KMP算法重写的意义在哪儿？为何不用String#indexOf方法？

**Comment by tgiwu** [comment]
意义在于去除指针回溯 效率比string indexof高发自我的华为手机-------- 原始邮件 --------发件人： Golden Looly ***@***.***>日期： 2021年8月23日周一 半夜11:25收件人： dromara/hutool ***@***.***>抄送： tgiwu ***@***.***>, Author ***@***.***>主    题： Re: [dromara/hutool] kmp 重写indexOf (#1780)

KMP算法重写的意义在哪儿？为何不用String#indexOf方法？

**Comment by xlgo** [comment]
`@Test
    public void test(){
        String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
        String pat = "dfseeeee";
        StopWatch st = new StopWatch();
        st.start("kmp");
        int c = 1_000_000;
        for (int i = 1 ; i<c;i++){
            indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }

    /**
     * kmp算法重写String类的indexOf方法
     * @param master     主字符串
     * @param pattern	 要查找的字符串
     * @return           索引值，未找到返回-1
     */
    public static int indexOf(String master, String pattern) {
        if (pattern.length() > master.length()) return -1; //与jdk保持一致，此处忽略空判断

        char[] masterChars = master.toCharArray(), patternChars = pattern.toCharArray();

        if (patternChars.length == 1) {
            for (int i = 0; i < masterChars.length; i++) {
                if (masterChars[i] == patternChars[0]) return i;
            }
            return -1;
        }

        int i = 0, j = 0;

        int[] next = getNext(pattern);

        while (i < masterChars.length && j < patternChars.length) {
            if (j == -1 || masterChars[i] == patternChars[j]) {
                i++;
                j++;
            } else {
                j = next[j];
            }
        }

        if (j == patternChars.length) {
            return i - j;
        } else {
            return -1;
        }
    }

    private static int[] getNext(String s) {
        char[] chars = s.toCharArray();

        int[] next = new int[chars.length];

        next[0] = -1;
        int j = 0;
        int k = -1;

        while (j < chars.length - 1) {
            if (k == -1 || chars[j] == chars[k]) {
                if (chars[++j] == chars[++k]) {
                    next[j] = next[k];
                } else {
                    next[j] = k;
                }
            } else {
                k = next[k];
            }
        }

        return next;
    }

    /**
     * 计算包含
     * @param master 	主字符串
     * @param pattern	要包含的字符串
     * @return	是否包含
     */
    public static boolean contains(String master, String pattern) {
        return -1 != indexOf(master, pattern);
    }`




`StopWatch '测试': running time = 339667400 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
334760400  099%  kmp
004907000  001%  jdk`







`StopWatch st = new StopWatch("测试");
        st.start("kmp");
        int c = 1_000_000;
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "dfseeeee";
            indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "dfseeeee";
            str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());`


`StopWatch '测试': running time = 294738600 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
291918100  099%  kmp
002820500  001%  jdk`







`    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("kmp");
        int c = 1_000_000;
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "b.zglfdmhf";
            indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "b.zglfdmhf";
            str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }`

`    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("kmp");
        int c = 1_000_000;

        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = RandomUtil.randomString(1);
            indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = RandomUtil.randomString(1);
            str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }`


`StopWatch '测试': running time = 289576600 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
242441000  084%  kmp
047135600  016%  jdk`



`    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("kmp");
        int c = 1_000_000;

        for (int i = 1 ; i<c;i++){
            String str = RandomUtil.randomString(30);
            String pat = RandomUtil.randomString(1);
            indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            String str = RandomUtil.randomString(30);
            String pat = RandomUtil.randomString(2);
            str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }`

`StopWatch '测试': running time = 727249900 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
500834700  069%  kmp
226415200  031%  jdk`




`    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("jdk");
        int c = 1_000_000;

        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = RandomUtil.randomString(2);
            str.indexOf(pat);
        }
        st.stop();
        st.start("kmp");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = RandomUtil.randomString(2);

            indexOf(str,pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }`

`StopWatch '测试': running time = 462652000 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
130776800  028%  jdk
331875200  072%  kmp`








`@Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("kmp");
        int c = 1_000_000;

        for (int i = 1 ; i<c;i++){
            String str = RandomUtil.randomString(30);
            String pat = RandomUtil.randomString(1);
            //indexOf(str,pat);
        }
        st.stop();
        st.start("jdk");
        for (int i = 1 ; i<c;i++){
            String str = RandomUtil.randomString(30);
            String pat = RandomUtil.randomString(2);
            //str.indexOf(pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }`

`StopWatch '测试': running time = 707427300 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
474558500  067%  kmp
232868800  033%  jdk`   
**性能差异来源于RandomUtil内存的消耗，垃圾回收。所以跟jdk的indexOf比，结果显而易见**

**Comment by xlgo** [comment]
``` java
    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("jdk");
        int c = 1_000_000;

        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "rb.zglfdmh";
            str.indexOf(pat);
        }
        st.stop();
        st.start("kmp");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "rb.zglfdmh";

            indexOf(str,pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }
```
```  T1
StopWatch '测试': running time = 250531500 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
004807500  002%  jdk
245724000  098%  kmp

```
``` T2
StopWatch '测试': running time = 242612800 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
004879100  002%  jdk
237733700  098%  kmp
```




``` java
    @Test
    public void test(){

        StopWatch st = new StopWatch("测试");
        st.start("jdk");
        int c = 100_000_000;

        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "asdf2mh";
            str.indexOf(pat);
        }
        st.stop();
        st.start("kmp");
        for (int i = 1 ; i<c;i++){
            String str = "sal;jdgo9b c,xvhtrb.zglfdmhfosdjhksghzxlhvkyqewob,vxzasf";
            String pat = "asdf2mh";

            indexOf(str,pat);
        }
        st.stop();
        System.out.println(st.prettyPrint());
    }
```
``` T1
StopWatch '测试': running time = 18901033600 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
005199300  000%  jdk
18895834300  100%  kmp

```
``` T2
StopWatch '测试': running time = 17787569700 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
005042100  000%  jdk
17782527600  100%  kmp


```

**Comment by xlgo** [comment]
17782527600/5042100
245724000   /4807500     

提升100倍调用次数，耗时 多了两个0 ，  jdk 几乎不变。
随机字符耗时严重，影响他们结果。 单还是相差不少
```
StopWatch '测试': running time = 2809949500 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
2412605500  086%  kmp
397344000  014%  jdk
```

**Comment by looly** [comment]
正解。我想应该是toCharArray导致的数组复制耗费了时间，还是老实用JDK的吧。

**Comment by tgiwu** [comment]
不能直接访问String的value 
只想到消除没必要的对比，没考虑对象转换和复制的事  

-_-!!

多谢各位帮忙验证！

**Pull request closed without merging**
